spring:
  application:
    name: chefs
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0